### ISSUE TITLE
Server crashing: Ticking tile entity, tile.atomicscience:accelerator

### ISSUE THREAD

**Issue by AmiT177** [BuiltBrokenModding/Atomic-Science#35]
https://pastebin.com/jgvmPwA4

Any ideas?

**Comment by DarkGuardsman** [comment]
We do not support the old versions of the mod. Especially since the old code is in Chinese and is nowhere close to the current code. 

My guess is something tries to act on an entity with bad data. However, I can't read the old code without running it through a translators.

------------------------
Minecraft Version: 1.5.2
```
java.lang.NullPointerException
    at atomicscience.fanwusu.EWuSu.func_70088_a(EWuSu.java:85)

    at net.minecraft.entity.Entity.<init>(Entity.java:338)

    at atomicscience.fanwusu.EWuSu.<init>(EWuSu.java:44)

    at atomicscience.fanwusu.EWuSu.<init>(EWuSu.java:53)

    at atomicscience.fanwusu.TJiaSuQi.func_70316_g(TJiaSuQi.java:139)
```
